### ISSUE TITLE
after upgrade to homeassistant 25.06 the integration dosent work

### ISSUE THREAD

**Issue by Jens41970** [jpcornil-git/HA-sma#29]
Hello the integration works fine till upgrade to Homeassistant 25.6
 how can i fix the problem?

**Comment by jpcornil-git** [comment]
Could you  enable/collect and attach logs for this integration ? I'll run some tests with 25.6 as well

**Comment by Jens41970** [comment]
Hi Here are the Log ‘s wit the two different versions of homeassistant

 

Mit freundlichen Grüßen

Jens Reichardt

**Comment by jpcornil-git** [comment]
Hi Jens,
Could you upload your logs in github directly (email attachements are not supported)
In the meantime, I ran version v2.2.2 of this integration with HA 2025.6.3 and everything looks OK, what version of the integration are you using ?

**Comment by Jens41970** [comment]
Hi  irun the 2.2.2 version and here the log  
[home-assistant_sma_webbox_2025-07-12T17-13-28.748Zwith homeassistatnt2025.5.log](https://github.com/user-attachments/files/21236514/home-assistant_sma_webbox_2025-07-12T17-13-28.748Zwith.homeassistatnt2025.5.log)
[home-assistant_sma_webbox_2025-07-12T17-27-06.701 Homeassistant 2025.7.log](https://github.com/user-attachments/files/21236515/home-assistant_sma_webbox_2025-07-12T17-27-06.701.Homeassistant.2025.7.log)

**Comment by jpcornil-git** [comment]
I see the following error in `home-assistant_sma_webbox_2025-07-12T17-27-06.701.Homeassistant.2025.7.log`
```
2025-07-12 19:25:15.162 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.178.21 for sma_webbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/altsma_webbox/__init__.py", line 137, in async_setup_entry
    await hass.config_entries.async_forward_entry_setup(entry, Platform.SENSOR)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```
and the following warning in `home-assistant_sma_webbox_2025-07-12T17-13-28.748Zwith.homeassistatnt2025.5.log`
```
2025-07-11 13:26:58.980 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'altsma_webbox' calls async_forward_entry_setup for integration, sma_webbox with title: 192.168.178.21 and entry_id: d7af8b0ec6ee99777aabd4489fde3e6a, which is deprecated, await async_forward_entry_setups instead at custom_components/altsma_webbox/__init__.py, line 137: await hass.config_entries.async_forward_entry_setup(entry, Platform.SENSOR). This will stop working in Home Assistant 2025.6, please report it to the author of the 'altsma_webbox' custom integration

```
You seem to be using a version older than v2.1.1 (version that handled deprecation of `async_forward_entry_setup`  in 2025.6)

A few strange things related to sma_webbox:
- I see two  warnings for the sma_webbox custom integration while I would expect only one ex, in `xxx2025.7.log`
```
2025-07-12 19:24:59.387 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sma_webbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
...
2025-07-12 19:24:59.392 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sma_webbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2
```
- I see `custom_components/altsma_webbox` for the sma_webbox path while I would expect `custom_components/webbox`
- I see that line 137 is mentionned for the `async_forward_entry_setup` error. That is possible up to version v2.1.1 but not latter ones.

=> All of this seems to point to usage of an older version than v2.1.1; error is also consistent with 2025.6 deprecation (OK with 2025.5 but not with 2025.7). 

May be there are two versions of the integration installed (two "custom integration" warnings, altsma_webbox ?) and only the oldest one is loaded ?

**Comment by Jens41970** [comment]
Hi thank you for your help now its working fine again
